name: Link Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  link-check:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --accept 200,429 '**/*.md' '**/*.rs' '**/*.toml'
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = 'Broken links detected';
            const body = 'The link checker found broken links. Please check the workflow logs for details.';

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['bug', 'documentation']
            });
